### ISSUE TITLE
Incorrect missions displaying (too many, probably old ones)

### ISSUE THREAD

**Issue by svange** [tautomer/EDMasscacreMissionCompanion#8]
* MaccacreCompanion version: 1.2.5
* Python version: 3.7
* Operating System: Windows 10

### Description

After installing, I got the follow problem. As you can see, the tool reports 29 active missions with 14 being complete (the game only allows 20 missions in the mission log, so 29 is impossible). I believe the extra missions are from a previous run, but have already been turned in.

![image](https://user-images.githubusercontent.com/7166607/117860639-60b69c80-b245-11eb-8339-f4b5349d207a.png)

### What I Did

```
I uninstalled an older version of this tool (installed on 4/11 I think, don't remember the version), then installed the latest version using the link in the Readme for the installer. Problems arose after launching the new version.
```

**Comment by tautomer** [comment]
Hmm... This one doesn't seem to be what I wrote.

Are you sure this is not [aklakina/EliteMoney](https://github.com/aklakina/EliteMoney) or something else?

**Comment by svange** [comment]
Closed because I'm a moron. Sorry, and thanks!
